---
title: "Stock plotter"
author: "Kexin Xie"
output:
  pdf_document: default
  html_document:
    df_print: paged
params:
  symbols: AAPL
  show_code: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo    = as.logical(params$show_code),
    message = FALSE, 
    warning = FALSE
)
```

```{r}
library(tidyquant)
library(dplyr)
library(knitr)
```

This report contains market data for `r params$symbols`.  To make for something to plot, I suggest you pull 7 days worth of data.

```{r}
# Get data
stock_data_tbl <- tq_get(
        x    = params$symbols,
        from = today()-11, 
        to   = today()
    ) %>%
    select(symbol, date, adjusted)

kable(stock_data_tbl,caption="Last 7 days of market close")
```

```{r}
# Create plot with gain/loss
## you to do
plot(x=stock_data_tbl$date,y=stock_data_tbl$adjusted,
     xlab = "Date", ylab = "Adjusted price")
```

```{r}
# save data 
# do you want to have a single running RDS file, or a file for every time this runs
# up to you to decide
saveRDS(stock_data_tbl, "../data/StockPrice.RDS")
```
